services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo16@2025      
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  odoo16:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "10016:8069"
      - "20016:8072"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo16@2025
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
      - ./addons:/mnt/extra-addons:rw
      - ./etc:/etc/odoo:rw
      - odoo_data:/var/lib/odoo
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@example.com'    
      PGADMIN_DEFAULT_PASSWORD: 'admin123'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: unless-stopped
    depends_on:
      - db

volumes:
  db_data:
  odoo_data:
  pgadmin_data:
